.TH "MXL-ALIAS" "1" "July 2015" "mxl-alias 0.5.46" "User Commands"
.SH "NAME"
mxl-alias -- Manage file aliases.
.SH "USAGE"

.SP
mxl alias [\-\-global] <args> <@alias=file>
.br
mxl as [\-\-global] <args> <@alias=file>
.SH "DESCRIPTION"
.PP
Manage aliases using an @ notation.
.PP
Aliases are automatically added if they do not already exist the first time a 
.br
call to \fBsource\-file\fR succeeds and are re\-written to \fB~/.mxlrc.json\fR. The rc 
.br
file is created if it does not exist.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-global\fR: Operate on global aliases.
.EL
.SH "AUTOMATIC"
.PP
The rules for alias names created automatically are:
.BL
.IP "\[ci]" 4
When the file is \fBtmux.conf\fR use the name of the parent directory.
.IP "\[ci]" 4
When the file has a \fB.tmux.conf\fR extension concatenate the parent directory 
.br
name with the name of the file after the extension has been removed. The 
.br
delimiter for concatenation is \fB/\fR.
.EL
.PP
You may disable automatically adding aliases by modifying the \fBautoalias\fR 
.br
rc option.
.PP
Note that if you run a file that kills the current window (\fBunlink\-window\fR etc) 
.br
aliases will not be added automatically as the process will have been killed 
.br
before the success handler returns. To workaround this run from another window, 
.br
eg: \fBmxl ~/project\fR.
.SH "GLOBAL"
.PP
Global aliases are created in the default rc file when mxl is installed. They 
.br
are stored in \fBnode_modules/mxl/conf\fR and may not be deleted.
.SH "LAUNCH"
.PP
You may pass an alias reference to the \fBrun\fR command:

  mxl @project
.SH "LIST"
.PP
List user aliases:

  mxl alias
.PP
List user aliases and include global aliases:

  mxl alias \-a
.PP
List global aliases:

  mxl alias \-\-global
.SH "ADD"
.PP
To add or update an alias manually assign to the alias:

  mxl alias @project=/usr/local/project
.SH "DELETE"
.PP
Assign the empty string to delete an alias.

  mxl alias @project=
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
