.TH "MXL-VIEW" "1" "July 2015" "mxl-view 0.6.5" "User Commands"
.SH "NAME"
mxl-view -- View and edit configuration files.
.SH "USAGE"

.SP
mxl view <args>
.br
mxl vi <args>
.SH "DESCRIPTION"
.PP
Print the contents for configuration files or open in \fIEDITOR\fR.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
