.TH "MXL-ALIAS" "1" "July 2015" "mxl-alias 0.4.3" "User Commands"
.SH "NAME"
mxl-alias -- [object Object]
.SH "USAGE"

.SP
mxl alias <command> <args>
.br
mxl as <command> <args> 
.br
mxl as get <args> <alias> 
.br
mxl as add <args> <alias> <dir> 
.br
mxl as rm <args> <alias> 
.br
mxl as ls <args>
.SH "DESCRIPTION"
.PP
Aliases allow users to map names to commonly used locations, a location being a 
.br
directory containing a tmux command configuration.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Print an alias.
.IP "\[ci]" 4
\fBadd\fR: Add an alias.
.IP "\[ci]" 4
\fBrm\fR: Remove an alias.
.IP "\[ci]" 4
\fBls\fR: List aliases.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
