.TH "MXL-PRUNE" "1" "July 2015" "mxl-prune 0.5.44" "User Commands"
.SH "NAME"
mxl-prune -- Remove stale aliases.
.SH "USAGE"

.SP
mxl prune <args>
.br
mxl pr <args>
.SH "DESCRIPTION"
.PP
As files are moved or deleted aliases may get out of date, run the \fBprune\fR 
.br
command to remove alias entries for files that no longer exist.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
.SH "SEE ALSO"
.PP
mxl\-alias(1)
