.TH "MXL-ALIAS" "1" "July 2015" "mxl-alias 0.5.2" "User Commands"
.SH "NAME"
mxl-alias -- Manage file aliases.
.SH "USAGE"

.SP
mxl alias <args> <@alias=file>
.br
mxl as <args> <@alias=file>
.SH "DESCRIPTION"
.PP
Manage aliases using an @ notation.
.PP
Aliases are automatically added if they do not already exist the first time a 
.br
call to \fBsource\-file\fR succeeds for the file.
.SH "LAUNCH"
.PP
You may pass an alias reference to the \fBrun\fR command:

  mxl @alias\-name
.SH "LIST"
.PP
List aliases:

  mxl alias
.SH "ADD"
.PP
To add or update an alias manually assign to the alias:

  mxl alias @project=/usr/local/project
.SH "DELETE"
.PP
Assign the empty string to delete an alias.

  mxl alias @project=
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
