.TH "MXL-LIST" "1" "July 2015" "mxl-list 0.5.59" "User Commands"
.SH "NAME"
mxl-list -- List configuration files.
.SH "USAGE"

.SP
mxl list <args>
.br
mxl ls <args>
.SH "DESCRIPTION"
.PP
List configuration files, preferring an index file \fBtmux.conf\fR by default. Use the \fB\-a\fR option to list all configuration files in a given directory and \fB\-r\fR to perform a recursive search.
.PP
When the \fB\-a\fR and \fB\-r\fR options are combined the search is recursive, \fB\-r\fR takes precedence.
.PP
The list command is an alias for \fBsource \-\-noop\fR.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
