.TH "MXL-LIST" "1" "July 2015" "mxl-list 0.5.13" "User Commands"
.SH "NAME"
mxl-list -- List configuration files.
.SH "USAGE"

.SP
mxl list <args>
.br
mxl ls <args>
.SH "DESCRIPTION"
.PP
List configuration files, preferring an index file \fBtmux.conf\fR by default. Use 
.br
the \fB\-a\fR option to list all configuration files in a given directory and \fB\-r\fR to
.br
perform a recursive search.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
