.TH "MXL-REMOVE" "1" "July 2015" "mxl-remove 0.6.4" "User Commands"
.SH "NAME"
mxl-remove -- Remove aliases by pattern match.
.SH "USAGE"

.SP
mxl remove <args> <pattern...>
.br
mxl rm <args> <pattern...>
.SH "DESCRIPTION"
.PP
Removes user aliases by regular expression pattern match, global aliases may not be deleted.
.PP
All unparsed arguments and values given to \fB\-p | \-\-pattern\fR are compiled to regular expressions and matched against the keys for the user aliases.
.PP
Matched alias keys are deleted and the aliases are re\-written unless \fB\-\-noop\fR is specified.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
