.TH "MXL-RUN" "1" "July 2015" "mxl-run 0.5.4" "User Commands"
.SH "NAME"
mxl-run -- Run tmux commands (source-file).
.SH "USAGE"

.SP
mxl run [\-e] [\-e|\-\-each] <args> <file> <dir> <:pattern> <@alias>
.br
mxl r [\-e] [\-e|\-\-each] <args> <file> <dir> <:pattern> <@alias>
.SH "DESCRIPTION"
.PP
Invokes \fBtmux source\-file\fR with the configuration files found by evaluating 
.br
the arguments, use the \fB\-\-noop\fR option to inspect what would be executed.
.PP
Arguments can be directories, files, alias references and file pattern matching 
.br
expressions.
.PP
See mxl\-alias(1) for more information on aliases.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-e, \-\-each\fR: Iterate child directories and set \fB\-c\fR for each directory.
.EL
.SH "ENVIRONMENT"
.PP
Before calls to \fBsource\-file\fR the following environment variables are set 
.br
using \fBset\-environment \-g\fR:
.BL
.IP "\[ci]" 4
\fBmxl_file\fR: The path to the configuration file.
.IP "\[ci]" 4
\fBmxl_filename\fR: The name of the configuration file.
.IP "\[ci]" 4
\fBmxl_cwd\fR: The working directory for the \fBtmux\fR process.
.IP "\[ci]" 4
\fBmxl_cwdname\fR: The name of the working directory.
.EL
.SH "EXAMPLES"
.PP
Source \fBtmux.conf\fR in the current working directory:

  mxl
.PP
Source a file by directory:

  mxl /usr/local/project
.PP
Source all \fB*.tmux.conf\fR files in the current working directory (and \fBtmux.conf\fR 
.br
if present):

  mxl \-a
.PP
Use a pattern match on the filename to filter results returned with \fB\-a\fR using 
.br
the \fB\-p\fR option:

  mxl \-a \-p '^test'
.PP
If a pattern matches multiple files and the \fB\-a\fR option is not given an 
.br
ambiguous match error is returned.
.PP
Source a file by alias reference:

  mxl @project
.PP
Source with multiple arguments:

  mxl @project @alt\-project /usr/local/project
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
.SH "SEE ALSO"
.PP
mxl\-alias(1), mxl\-list(1)
