.TH "MXL-INSTALL" "1" "July 2015" "mxl-install 0.5.30" "User Commands"
.SH "NAME"
mxl-install
.SH "USAGE"

.SP
mxl install [\-f] [\-f|\-\-force] <args>
.br
mxl i [\-f] [\-f|\-\-force] <args>
.SH "DESCRIPTION"
.PP
Install alias files.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-f, \-\-force\fR: Force overwrite existing files.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
