.TH "MXL-ATTACH" "1" "July 2015" "mxl-attach 0.5.63" "User Commands"
.SH "NAME"
mxl-attach
.SH "USAGE"

.SP
mxl attach <args> <name>
.br
mxl att <args> <name>
.br
mxl a <args> <name>
.SH "DESCRIPTION"
.PP
Attach to a session.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
