.TH "MXL-KILL" "1" "July 2015" "mxl-kill 0.5.54" "User Commands"
.SH "NAME"
mxl-kill -- Kill sessions, windows and panes.
.SH "USAGE"

.SP
mxl kill [\-SWP] [\-S] [\-W] [\-P] <args> <pattern...>
.br
mxl k [\-SWP] [\-S] [\-W] [\-P] <args> <pattern...>
.SH "DESCRIPTION"
.PP
Destroy sessions, windows and panes using regular expression patterns.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-S\fR: Kill sessions.
.IP "\[ci]" 4
\fB\-W\fR: Kill windows (default).
.IP "\[ci]" 4
\fB\-P\fR: Kill panes.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
