.TH "MXL-INDEX" "1" "July 2015" "mxl-index 0.5.9" "User Commands"
.SH "NAME"
mxl-index -- Generate alias index.
.SH "USAGE"

.SP
mxl index <args> <dir...>
.br
mxl in <args> <dir...>
.SH "DESCRIPTION"
.PP
Recursively searches the specified directories for configuration files and adds 
.br
them as aliases unless the \fB\-\-noop\fR option is specified.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
.SH "SEE ALSO"
.PP
mxl\-alias(1)
