.TH "MXL-EXEC" "1" "July 2015" "mxl-exec 0.6.4" "User Commands"
.SH "NAME"
mxl-exec -- Execute a command in a pane.
.SH "USAGE"

.SP
mxl exec <args> <cmd>
.br
mxl ex <args> <cmd>
.SH "DESCRIPTION"
.PP
Execute a command in a new pane and kill the pane if the command succeeds, otherwise the pane remains open to inspect errors.
.PP
Focus is \fInot\fR given to the new pane for the command.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
