.TH "MXL-RESHUFFLE" "1" "July 2015" "mxl-reshuffle 0.5.65" "User Commands"
.SH "NAME"
mxl-reshuffle -- Reshuffle window indices to be sequential.
.SH "USAGE"

.SP
mxl reshuffle <args>
.br
mxl rs <args>
.SH "DESCRIPTION"
.PP
Alias for \fB:move\-window \-r\fR.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
