.TH "MXL-TEMPLATE" "1" "July 2015" "mxl-template 0.5.18" "User Commands"
.SH "NAME"
mxl-template -- Manage file templates.
.SH "USAGE"

.SP
mxl template <command> <args>
.br
mxl tpl <command> <args> 
.br
mxl tpl list <args>
.SH "DESCRIPTION"
.PP
List, copy, link, show and edit templates.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBlist, ls\fR: List template files.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
