.TH "MXL" "1" "July 2015" "mxl 0.4.7" "User Commands"
.SH "NAME"
mxl -- Tmux launcher.
.SH "USAGE"

.SP
mxl <command> [\-avh] [\-\-color|\-\-no\-color] [\-a] [\-\-noop] [\-v]
.br
    [\-h|\-\-help] [\-\-version] [\-c=<dir>] <args>
.SH "DESCRIPTION"
.PP
When no command is specified the \fBrun\fR command is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBrun, r\fR: Run tmux commands (source\-file).
.IP "\[ci]" 4
\fBls\fR: List command files.
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-h, \-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-c=[dir]\fR: Working directory used for \fBsource\-file\fR.
.IP "\[ci]" 4
\fB\-a\fR: Launch all matched files.
.IP "\[ci]" 4
\fB\-\-noop\fR: Print matched files, do not call \fBsource\-file\fR.
.IP "\[ci]" 4
\fB\-v\fR: Print more information.
.IP "\[ci]" 4
\fB\-\-version\fR: Print version and exit.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/mxl/issues.
