#!/usr/bin/env node

var fs = require('fs')
  , path = require('path')
  , utils = require('../lib/util')
  , file = utils.file
  , folder = utils.folder
  , find = require('fs-find')
  , base = path.normalize(path.join(__dirname, '..', 'conf', 'tpl'))
  , key = utils.key
  , rcfile = path.normalize(path.join(__dirname, '..', '.mxlrc.json'))
  , rc = require(rcfile);

function finder(next) {
  var opts = {file: file, folder: folder};
  find(base, opts, function onFind(err, results) {
    if(err) {
      return next(err) ;
    } 
    next(null, results);
  });
}

function error(err) {
  console.error(err.stack);
  process.exit(1)
}

finder(function onFind(err, results) {
  if(err) {
    return error(err);
  }
  var id;
  rc.alias = rc.alias || {};

  results.forEach(function(info) {
    id = key(info.file);
    rc.alias[id] = {
      file: info.file, 
      key: id 
    }
  })

  try {
    fs.writeFileSync(rcfile, JSON.stringify(rc, undefined, 2));
  }catch(err) {
    return error(err);
  }

  console.log('wrote %d aliases to %s', results.length, rcfile);
});
