#!/usr/bin/env node
// vim: set ft=javascript:

var fs = require('fs')
  , path = require('path')
  , util = require('util')
  , async = require('async')
  , files = fs.readdirSync('conf/tpl');

async.mapSeries(files, function(nm, cb) {
  console.log('### %s\n', nm);
  console.log(
  '```\n' + fs.readFileSync(
    path.join(__dirname, '..', 'conf', 'tpl', nm)) + '```\n');
  cb();
}, function(err, results) {
  if(err) {
    console.error(err);
    process.exit(1);
  }
})
